### PR TITLE
bug fix

### PR DESCRIPTION
**Pull request by qunoissue**
* Fix implement of [`rawSqlProcessRow`](https://hackage.haskell.org/package/persistent-2.14.5.2/docs/Database-Persist-Sql.html#v:rawSqlProcessRow)
* Change 'persistent' version bounds such that n-tuples (n > 12) are instance of [`RawSql`](https://hackage.haskell.org/package/persistent-2.14.5.2/docs/Database-Persist-Sql.html#t:RawSql)
* Remove Strict extension because it was causing internal error in [`rawSql`](https://hackage.haskell.org/package/persistent-2.14.5.1/docs/Database-Persist-Sql.html#v:rawSql)

### CODE REVIEW

**Comment by arowM** [comment]
@qunoissue 
Thanks!
Is it possible not to remove Strict extension, but resolve with lazy operator `~`?
cf., https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/strict.html#strict-by-default-data-types

I would like to keep Strict extension on if possible, but if it is difficult due to evilness of the template haskell that persistent uses, it can be turned off.

**Comment by qunoissue** [comment]
@arowM 

> Is it possible not to remove Strict extension, but resolve with lazy operator `~`?

It is possible by adding lazy operators to definitions of  `rawSqlCols`.

<details><summary>details</summary>

```haskell

instance
  ( RawSql (Single v1)
  , KnownSymbol k1
  ) => RawSql (KVList '[ k1 := v1 ]) where
  rawSqlCols f ~r =
    rawSqlCols f (Single (KVList.get (ListKey :: ListKey k1) r :: v1))
  rawSqlColCountReason r =
    rawSqlColCountReason (Single (KVList.get (ListKey :: ListKey k1) r :: v1))
  rawSqlProcessRow vs = do
    (Single v1) <- rawSqlProcessRow vs
    pure $
      KVList.empty
        &= (ListKey :: ListKey k1) := v1

instance
  ( RawSql (Single v1), RawSql (Single v2)
  , KnownSymbol k1, KnownSymbol k2
  , kvs ~ '[ k1 := v1, k2 := v2 ]
  , KVList.HasKey k1 kvs v1, KVList.HasKey k2 kvs v2
  ) => RawSql (KVList '[ k1 := v1, k2 := v2 ]) where
  rawSqlCols f ~r =
    rawSqlCols f
      ( Single (KVList.get (ListKey :: ListKey k1) r :: v1)
      , Single (KVList.get (ListKey :: ListKey k2) r :: v2)
      )
  rawSqlColCountReason r =
    rawSqlColCountReason
      ( Single (KVList.get (ListKey :: ListKey k1) r :: v1)
      , Single (KVList.get (ListKey :: ListKey k2) r :: v2)
      )
  rawSqlProcessRow vs = do
    (Single v1, Single v2) <- rawSqlProcessRow vs
    pure $
      KVList.empty
        &= (ListKey :: ListKey k1) := v1
        &= (ListKey :: ListKey k2) := v2

...
```

</details>

Is this your intended solution?
(I'm not aware of specific benefit of adding Strict extension...)

**Comment by qunoissue** [comment]
It appears that CI is not running due to permission issues. Could you please approve it?

**Comment by arowM** [comment]
@qunoissue 
Thanks. It seems good. 🌷
Laziness of Haskell is good for tuning performance, but it can easily cause memory leak. I prefer to make Strict default not to think about such potential risks.

**Comment by qunoissue** [comment]
@arowM
I fixed to restore the Strict extension. Please check again.

> Laziness of Haskell is good for tuning performance, but it can easily cause memory leak. I prefer to make Strict default not to think about such potential risks.

Thanks for the explanation! I understand.

**Comment by arowM** [comment]
Looks good, thanks! 🎉

**Comment by arowM** [comment]
Released as v 0.2.0.1
https://hackage.haskell.org/package/type-level-kv-list-persistent

**Pull request merged**
